const companies = [
  {
    "_id": "cmp001",
    "companyName": "Knight Frank",
    "website": "https://www.knightfrank.co.uk",
    "industry": "Real Estate",
    "companySize": "1000+",
    "country": "United Kingdom",
    "city": "London",
    "address": "55 Baker Street, London",
    "phone": "+44 20 7861 1000",
    "email": "info@knightfrank.co.uk",
    "linkedin": "https://linkedin.com/company/knight-frank",
    "logo": "https://placehold.co/80x80?text=KF",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr001",
    "notes": "Premium commercial property consultancy.",
    "createdAt": "2026-01-10T09:30:00Z",
    "updatedAt": "2026-01-10T09:30:00Z"
  },
  {
    "_id": "cmp002",
    "companyName": "Savills",
    "website": "https://www.savills.co.uk",
    "industry": "Real Estate",
    "companySize": "1000+",
    "country": "United Kingdom",
    "city": "London",
    "address": "33 Margaret Street",
    "phone": "+44 20 7499 8644",
    "email": "info@savills.co.uk",
    "linkedin": "https://linkedin.com/company/savills",
    "logo": "https://placehold.co/80x80?text=SV",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr002",
    "notes": "",
    "createdAt": "2026-01-12T10:00:00Z",
    "updatedAt": "2026-01-12T10:00:00Z"
  },
  {
    "_id": "cmp003",
    "companyName": "CBRE UK",
    "website": "https://www.cbre.co.uk",
    "industry": "Commercial Property",
    "companySize": "1000+",
    "country": "United Kingdom",
    "city": "Manchester",
    "address": "3 Hardman Square",
    "phone": "+44 161 233 0600",
    "email": "uk@cbre.com",
    "linkedin": "https://linkedin.com/company/cbre",
    "logo": "https://placehold.co/80x80?text=CB",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr003",
    "notes": "",
    "createdAt": "2026-01-15T12:00:00Z",
    "updatedAt": "2026-01-15T12:00:00Z"
  },
  {
    "_id": "cmp004",
    "companyName": "JLL UK",
    "website": "https://www.jll.co.uk",
    "industry": "Commercial Real Estate",
    "companySize": "1000+",
    "country": "United Kingdom",
    "city": "Birmingham",
    "address": "1 Colmore Square",
    "phone": "+44 121 634 8400",
    "email": "uk@jll.com",
    "linkedin": "https://linkedin.com/company/jll",
    "logo": "https://placehold.co/80x80?text=JL",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr001",
    "notes": "",
    "createdAt": "2026-01-18T09:00:00Z",
    "updatedAt": "2026-01-18T09:00:00Z"
  },
  {
    "_id": "cmp005",
    "companyName": "Colliers UK",
    "website": "https://www.colliers.com",
    "industry": "Real Estate",
    "companySize": "500-1000",
    "country": "United Kingdom",
    "city": "Leeds",
    "address": "Platform Building",
    "phone": "+44 113 244 6444",
    "email": "info@colliers.com",
    "linkedin": "https://linkedin.com/company/colliers",
    "logo": "https://placehold.co/80x80?text=CL",
    "status": "Active",
    "verified": false,
    "assignedTo": "usr002",
    "notes": "",
    "createdAt": "2026-01-20T14:00:00Z",
    "updatedAt": "2026-01-20T14:00:00Z"
  },
  {
    "_id": "cmp006",
    "companyName": "Cushman & Wakefield",
    "website": "https://www.cushmanwakefield.com",
    "industry": "Commercial Property",
    "companySize": "1000+",
    "country": "United Kingdom",
    "city": "Glasgow",
    "address": "1 Waterloo Street",
    "phone": "+44 141 248 1000",
    "email": "uk@cushwake.com",
    "linkedin": "https://linkedin.com/company/cushman-wakefield",
    "logo": "https://placehold.co/80x80?text=CW",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr003",
    "notes": "",
    "createdAt": "2026-01-22T11:30:00Z",
    "updatedAt": "2026-01-22T11:30:00Z"
  },
  {
    "_id": "cmp007",
    "companyName": "Bidwells",
    "website": "https://www.bidwells.co.uk",
    "industry": "Property Consultancy",
    "companySize": "500-1000",
    "country": "United Kingdom",
    "city": "Cambridge",
    "address": "Trumpington Road",
    "phone": "+44 1223 559200",
    "email": "info@bidwells.co.uk",
    "linkedin": "https://linkedin.com/company/bidwells",
    "logo": "https://placehold.co/80x80?text=BD",
    "status": "Inactive",
    "verified": false,
    "assignedTo": "usr001",
    "notes": "",
    "createdAt": "2026-01-25T15:00:00Z",
    "updatedAt": "2026-01-25T15:00:00Z"
  },
  {
    "_id": "cmp008",
    "companyName": "Lambert Smith Hampton",
    "website": "https://www.lsh.co.uk",
    "industry": "Commercial Property",
    "companySize": "500-1000",
    "country": "United Kingdom",
    "city": "Bristol",
    "address": "Temple Quay",
    "phone": "+44 117 926 6666",
    "email": "info@lsh.co.uk",
    "linkedin": "https://linkedin.com/company/lambert-smith-hampton",
    "logo": "https://placehold.co/80x80?text=LSH",
    "status": "Active",
    "verified": false,
    "assignedTo": "usr002",
    "notes": "",
    "createdAt": "2026-01-27T13:45:00Z",
    "updatedAt": "2026-01-27T13:45:00Z"
  },
  {
    "_id": "cmp009",
    "companyName": "Avison Young",
    "website": "https://www.avisonyoung.com",
    "industry": "Commercial Real Estate",
    "companySize": "500-1000",
    "country": "United Kingdom",
    "city": "Edinburgh",
    "address": "Exchange Crescent",
    "phone": "+44 131 220 4844",
    "email": "info@avisonyoung.com",
    "linkedin": "https://linkedin.com/company/avison-young",
    "logo": "https://placehold.co/80x80?text=AY",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr003",
    "notes": "",
    "createdAt": "2026-01-28T09:30:00Z",
    "updatedAt": "2026-01-28T09:30:00Z"
  },
  {
    "_id": "cmp010",
    "companyName": "Fisher German",
    "website": "https://www.fishergerman.co.uk",
    "industry": "Property Consultancy",
    "companySize": "200-500",
    "country": "United Kingdom",
    "city": "Nottingham",
    "address": "Canal Street",
    "phone": "+44 115 945 5780",
    "email": "info@fishergerman.co.uk",
    "linkedin": "https://linkedin.com/company/fisher-german",
    "logo": "https://placehold.co/80x80?text=FG",
    "status": "Active",
    "verified": true,
    "assignedTo": "usr001",
    "notes": "",
    "createdAt": "2026-02-01T08:30:00Z",
    "updatedAt": "2026-02-01T08:30:00Z"
  }
]


export default companies;