const contacts = [
  {
    "_id": "con001",
    "company": "cmp001",
    "firstName": "James",
    "lastName": "Anderson",
    "jobTitle": "Managing Director",
    "department": "Management",
    "email": "james.anderson@knightfrank.co.uk",
    "phone": "+44 7700 900001",
    "linkedin": "https://linkedin.com/in/jamesanderson",
    "country": "United Kingdom",
    "city": "London",
    "status": "Active",
    "notes": "Primary decision maker.",
    "createdAt": "2026-01-15T10:00:00Z",
    "updatedAt": "2026-01-15T10:00:00Z"
  },
  {
    "_id": "con002",
    "company": "cmp001",
    "firstName": "Emily",
    "lastName": "Wilson",
    "jobTitle": "Sales Manager",
    "department": "Sales",
    "email": "emily.wilson@knightfrank.co.uk",
    "phone": "+44 7700 900002",
    "linkedin": "https://linkedin.com/in/emilywilson",
    "country": "United Kingdom",
    "city": "London",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-16T09:00:00Z",
    "updatedAt": "2026-01-16T09:00:00Z"
  },
  {
    "_id": "con003",
    "company": "cmp002",
    "firstName": "Oliver",
    "lastName": "Brown",
    "jobTitle": "Head of Acquisitions",
    "department": "Investment",
    "email": "oliver.brown@savills.co.uk",
    "phone": "+44 7700 900003",
    "linkedin": "https://linkedin.com/in/oliverbrown",
    "country": "United Kingdom",
    "city": "London",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-17T10:00:00Z",
    "updatedAt": "2026-01-17T10:00:00Z"
  },
  {
    "_id": "con004",
    "company": "cmp002",
    "firstName": "Sophia",
    "lastName": "Taylor",
    "jobTitle": "Business Development Manager",
    "department": "Business Development",
    "email": "sophia.taylor@savills.co.uk",
    "phone": "+44 7700 900004",
    "linkedin": "https://linkedin.com/in/sophiataylor",
    "country": "United Kingdom",
    "city": "London",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-18T11:00:00Z",
    "updatedAt": "2026-01-18T11:00:00Z"
  },
  {
    "_id": "con005",
    "company": "cmp003",
    "firstName": "George",
    "lastName": "Martin",
    "jobTitle": "Director",
    "department": "Commercial",
    "email": "george.martin@cbre.com",
    "phone": "+44 7700 900005",
    "linkedin": "https://linkedin.com/in/georgemartin",
    "country": "United Kingdom",
    "city": "Manchester",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-19T10:30:00Z",
    "updatedAt": "2026-01-19T10:30:00Z"
  },
  {
    "_id": "con006",
    "company": "cmp004",
    "firstName": "Charlotte",
    "lastName": "Evans",
    "jobTitle": "Regional Manager",
    "department": "Operations",
    "email": "charlotte.evans@jll.com",
    "phone": "+44 7700 900006",
    "linkedin": "https://linkedin.com/in/charlotteevans",
    "country": "United Kingdom",
    "city": "Birmingham",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-20T12:00:00Z",
    "updatedAt": "2026-01-20T12:00:00Z"
  },
  {
    "_id": "con007",
    "company": "cmp005",
    "firstName": "Harry",
    "lastName": "White",
    "jobTitle": "Property Consultant",
    "department": "Consulting",
    "email": "harry.white@colliers.com",
    "phone": "+44 7700 900007",
    "linkedin": "https://linkedin.com/in/harrywhite",
    "country": "United Kingdom",
    "city": "Leeds",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-21T09:00:00Z",
    "updatedAt": "2026-01-21T09:00:00Z"
  },
  {
    "_id": "con008",
    "company": "cmp006",
    "firstName": "Amelia",
    "lastName": "Walker",
    "jobTitle": "Senior Consultant",
    "department": "Sales",
    "email": "amelia.walker@cushwake.com",
    "phone": "+44 7700 900008",
    "linkedin": "https://linkedin.com/in/ameliawalker",
    "country": "United Kingdom",
    "city": "Glasgow",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-22T14:00:00Z",
    "updatedAt": "2026-01-22T14:00:00Z"
  },
  {
    "_id": "con009",
    "company": "cmp007",
    "firstName": "William",
    "lastName": "Scott",
    "jobTitle": "Estate Manager",
    "department": "Management",
    "email": "william.scott@bidwells.co.uk",
    "phone": "+44 7700 900009",
    "linkedin": "https://linkedin.com/in/williamscott",
    "country": "United Kingdom",
    "city": "Cambridge",
    "status": "Inactive",
    "notes": "",
    "createdAt": "2026-01-23T10:00:00Z",
    "updatedAt": "2026-01-23T10:00:00Z"
  },
  {
    "_id": "con010",
    "company": "cmp008",
    "firstName": "Isabella",
    "lastName": "Harris",
    "jobTitle": "Business Development Executive",
    "department": "Business Development",
    "email": "isabella.harris@lsh.co.uk",
    "phone": "+44 7700 900010",
    "linkedin": "https://linkedin.com/in/isabellaharris",
    "country": "United Kingdom",
    "city": "Bristol",
    "status": "Active",
    "notes": "",
    "createdAt": "2026-01-24T09:30:00Z",
    "updatedAt": "2026-01-24T09:30:00Z"
  }
];

export default contacts;
